[package]
name = "cce-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://git.lucas.co/cce-ui.git", rev = "84f1bae21c16852442b7895004418232612a0bb9" }
wayland-client = { version = "0.31", features = ["system"] }
calloop = "0.13.0"
libc = "0.2"
alacritty_terminal = "0.26.0"
log = "0.4"
env_logger = "0.11"
